apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-micrometer
  namespace: ${environment}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-micrometer
        appVersion: ${appVersion}
        configVersion: ${configVersion}
    spec:
      containers:
        - name: spring-micrometer
          image: jinternals/spring-micrometer-demo:${appVersion}
          ports:
            - name: http-port
              containerPort: 8080
          volumeMounts:
            - name: micrometer-config
              mountPath: /etc/micrometer-config
      volumes:
        - name: micrometer-config
          configMap:
           name: micrometer-config-${configVersion}
