kind: Service
apiVersion: v1
metadata:
  name: micrometer-service
  labels:
    app: micrometer-service
spec:
  type: NodePort
  selector:
    app: micrometer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: api
